import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ProductCartProvider } from "../contextProvider/Prod";
import Provider from "../contextProvider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eureka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <ProductCartProvider>
            <Navbar />
            {children}
            <Footer />
          </ProductCartProvider>
        </body>
      </Provider>
    </html>
  );
}
